name: Allen Mortgage
favicon: null
layout_spectrum: 0.32276
typography_spectrum: 0.48903
title: Allen Mortgage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f589c'
    - '#5a5a5a'
    - '#bdbdbd'
    - '#272727'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0
purpose: []
